### ISSUE TITLE
Take input of source language and target language from user via Command line argument

### ISSUE THREAD

**Issue by admirerr** [ContriHUB/TravelBuddy#1]
<img width="1440" alt="Screenshot 2023-10-06 at 12 24 46 AM" src="https://github.com/ContriHUB/TravelBuddy/assets/79766263/058e555d-99d9-4a2f-8727-f8aef07de827">

Now we are required to make changes in the code for  defining **source language** and **target language**. It would be more interactive if both of them is supplied by the user through command line argument :)

**Comment by mangalgithub** [comment]
Can you assign this issue to me.

**Comment by mangalgithub** [comment]
I can use fastApi for achieving this task.

**Comment by Nandika-A** [comment]
Hello @admirerr! I have resolved this issue in PR#4. I have used the sys module to get command line arguments.
