### ISSUE TITLE
Prevent overwriting of the file "output.mp3"

### ISSUE THREAD

**Issue by admirerr** [ContriHUB/TravelBuddy#3]
At present, when the model is run and executed, old file of the previous execution i.e.-`output.mp3` is overwrited with the new one having the same name. We don't want new file to replace old one, instead it must create a separate new file. For better result, try to place these files in a separate directory.

**Comment by Tejjus** [comment]
hey can I be assigned to this issue?

**Comment by avi-dey** [comment]
I can do this. Can I start working?

**Comment by krishna6245** [comment]
Can i work on this issue?
